### ISSUE TITLE
TypeError: _babelCore.OptionManager is not a function

### ISSUE THREAD

**Issue by febobo** [febobo/react-native-redux-FeInn#25]
Update react-native error
```
TypeError: _babelCore.OptionManager is not a function
    at compile (/Users/febobo/Documents/react/demo/demo/app/ysweb/node_modules/babel-register/lib/node.js:112:14)
    at loader (/Users/febobo/Documents/react/demo/demo/app/ysweb/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/febobo/Documents/react/demo/demo/app/ysweb/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/febobo/Documents/react/demo/demo/app/ysweb/node_modules/react-native/local-cli/cli.js:17:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

fix issue
change your package.json
```
"react-native": "^0.27.2",
``` 
to
```
"react-native": "0.27.2",
```

try run ```$ npm start```

**Comment by jyotiprakash111** [comment]
i have tried $npm start still not working.

TypeError: babel.OptionManager is not a constructor
    at compile (F:\React-Native\FluidTransitions\node_modules\@babel\register\lib\node.js:61:16)
    at compileHook (F:\React- 
    Native\FluidTransitions\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (F:\React-Native\FluidTransitions\node_modules\pirates\lib\index.js:86:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (F:\React- 
   Native\FluidTransitions\node_modules\pirates\lib\index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
