### ISSUE TITLE
安卓打包后闪退

### ISSUE THREAD

**Issue by skating507** [febobo/react-native-redux-FeInn#56]
安卓打包后闪退

**Comment by febobo** [comment]
有具体错误信息吗 ？ @skating507

**Comment by skating507** [comment]
com.facebook.react.modules.core.JavascriptException: Requiring unknown module "../../../update.json"., stack:
n@2:700
o@2:404
e@2:326
i@2:188
<unknown>@375:246
o@2:517
e@2:326
i@2:188
<unknown>@12:88
o@2:517
e@2:256
i@2:188
global code@556:9

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:148)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)
